// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSNc5OSjxJ_VWrdWDbA1Iz6ewmhHWlAI',
    appId: '1:324552479247:web:6466cdf5853908181c497a',
    messagingSenderId: '324552479247',
    projectId: 'cpdhome-407e4',
    authDomain: 'cpdhome-407e4.firebaseapp.com',
    storageBucket: 'cpdhome-407e4.firebasestorage.app',
    measurementId: 'G-CC0PSDS0RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5YVifeYtDMNmnI3NzQWs6sKmiex7vvRs',
    appId: '1:324552479247:android:701a8e18ab3f5ae41c497a',
    messagingSenderId: '324552479247',
    projectId: 'cpdhome-407e4',
    storageBucket: 'cpdhome-407e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTXHr41AleVcJ2ZM1h61HstDX6oyKd4Ns',
    appId: '1:324552479247:ios:db8007eeaba9fa7f1c497a',
    messagingSenderId: '324552479247',
    projectId: 'cpdhome-407e4',
    storageBucket: 'cpdhome-407e4.firebasestorage.app',
    iosBundleId: 'com.example.cpdAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTXHr41AleVcJ2ZM1h61HstDX6oyKd4Ns',
    appId: '1:324552479247:ios:db8007eeaba9fa7f1c497a',
    messagingSenderId: '324552479247',
    projectId: 'cpdhome-407e4',
    storageBucket: 'cpdhome-407e4.firebasestorage.app',
    iosBundleId: 'com.example.cpdAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmSNc5OSjxJ_VWrdWDbA1Iz6ewmhHWlAI',
    appId: '1:324552479247:web:30489a891a8763081c497a',
    messagingSenderId: '324552479247',
    projectId: 'cpdhome-407e4',
    authDomain: 'cpdhome-407e4.firebaseapp.com',
    storageBucket: 'cpdhome-407e4.firebasestorage.app',
    measurementId: 'G-9N3QG8DNHJ',
  );
}
